import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import GqlClient from '../graphql/apollo-client'
import { gql } from '@apollo/client'
import { Link } from '../types/Link'

type Props = {
  links: Link[]
}

const Home = ({links}: Props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Lista de Links</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Lista de Links
        </h1>

        <p className={styles.description}>
          Total de links: {links.length}
        </p>

        <div className={styles.grid}>
          {links.map((link, index) => (
            <a key={index} href={link.url} target="_blank" className={styles.card}>
              <h2>{link.title} &rarr;</h2>
              <p>{link.url}</p>
            </a>
          ))}
        </div>
      </main>
    </div>
  )
}

export default Home

export const getServerSideProps = async () => {
  const { data } = await GqlClient.query({
    query: gql`
      query {
        links {
          id
          url
          title
        }
      }
    `
  });

  return {
    props: {
      links: data.links
    }
  }
}